Add ecommerce related layouts
Voog/design-berlin pull request #110
Opened 2021-06-11 13:42 UTC by robertpih

Closes #107

2021-06-14 11:36 UTC, siimha commented
### Disaini ja funktsionaalsusega seotud küsimused.
Tooteleht:
1. Kuni 1500px laiuse ekraani puhul sisu max laius 744px, siis antud sisu joonduse loogika ei toimi (pildo tulp 60% ja sisu tulp 40%). Võimalkud lahendused oleks suurendada sisu maks laiust või tupade suhet nt 50/50 või 40/60. 
<img width="766" alt="Screenshot 2021-06-14 at 14 20 06" src="https://user-images.githubusercontent.com/35253483/121885207-8fc89e00-cd1c-11eb-8a0f-70e7c86159c4.png">
2. Kas parem tulp peaks liikuma scrolliga kaasa nagu Nuukis?
3. Kas mobiilis peaks parem tulp pildi alla liikuma?
5. Kas võtame kasutusele ka tootega sildid, seotud tooted?

Listingu leht:
1. Mis värvilahendust ja fonti peaksid lihtingu all olevad lingid ja nupud kasutama?
<img width="1193" alt="Screenshot 2021-06-14 at 14 16 07" src="https://user-images.githubusercontent.com/35253483/121885483-e209bf00-cd1c-11eb-807e-7d3da0ba56e5.png">
2. Kas listingu elemente peaks saama disainitööristast muuta? Kui jah, siis mida?
3. Kui lisame ka filtri, siis milline oleks selle välimus?

2021-06-14 12:02 UTC, tanelj requested changes
Esmane tagasiside.

2021-06-14 12:02 UTC, tanelj commented on components/lazy-image.tpl
> +  {%- assign sizes = "(min-width: " | append: _targetWidth | append: ") " | append: _targetWidth | append: 'px' -%}
Siin peab olema `append: "px) "`, sest media query peab alati olema ühikutega. Vaata ka vastavat parandust [Nuuki mallis](https://github.com/Voog/design-nuuk/pull/44/files)

2021-06-14 12:02 UTC, siimha requested changes

2021-06-22 11:44 UTC, hennrunnel commented
> ### Disaini ja funktsionaalsusega seotud küsimused
> **Tooteleht:**
> 
> 1. Kuni 1500px laiuse ekraani puhul sisu max laius 744px, siis antud sisu joonduse loogika ei toimi (pildo tulp 60% ja sisu tulp 40%). Võimalkud lahendused oleks suurendada sisu maks laiust või tupade suhet nt 50/50 või 40/60.

Proovime 50/50

> 
> 1. Kas parem tulp peaks liikuma scrolliga kaasa nagu Nuukis?

Jah

> 2. Kas mobiilis peaks parem tulp pildi alla liikuma?

Jah

> 3. Kas võtame kasutusele ka tootega sildid, seotud tooted?

Jah 

> 
> **Listingu leht:**
> 
> 1. Mis värvilahendust ja fonti peaksid lihtingu all olevad lingid ja nupud kasutama?
> 
> <img alt="Screenshot 2021-06-14 at 14 16 07" width="1193" src="https://user-images.githubusercontent.com/35253483/121885483-e209bf00-cd1c-11eb-807e-7d3da0ba56e5.png">

* Toote pealkiri — plaintext
* "Vaata lähemalt" ja "Lisa ostukorvi" — lingi stiil

> 
> 1. Kas listingu elemente peaks saama disainitööristast muuta? Kui jah, siis mida?

Muutujad võiksid olla samad, mis Nuukis: 
<img width="246" alt="image" src="https://user-images.githubusercontent.com/11610902/122918962-5e794f00-d368-11eb-92c5-0b9889163f38.png">



> 2. Kui lisame ka filtri, siis milline oleks selle välimus?

See vajab disaineri abi, mida praegu pole. Skipime.

2021-07-26 12:00 UTC, tanelj requested changes
Mõned teemad ikka leidsin, kuid suures pildis töötab kenasti!

* [ ] `submenu` komponen vajab refaktooringut. Ta ei tohiks kuvada "Product ja "product list" tüüpi layoutidega alalehti. Ning menüüd ennast peaks kuvatama vaid siis, kui tegu on edit mode'iga või seal on vähemalt üks nähtav  mitte tooteleht/listi leht.
![Screenshot 2021-07-26 at 14 16 03](https://user-images.githubusercontent.com/378755/126980372-4f2a3633-b686-448e-8ba3-c9713cc05f3d.png)
* [ ] Toote breadcrumb'is on muutmise vaates "add" nupule õhku vaja:
![Screenshot 2021-07-26 at 14 24 49](https://user-images.githubusercontent.com/378755/126981445-df327972-2d5d-4530-9cbc-b7cac7c396c2.png)

2021-07-29 12:07 UTC, tanelj requested changes
Toimib kenasti! Vaid ühe kommi panin.

2021-07-29 12:07 UTC, tanelj commented on components/product-item.tpl
> +        _targetWidth: '1280',
Toote listis on `_targetWidth: '1280'` päris palju. Nuukis on see sama väärtus nt 700 (https://github.com/Voog/design-nuuk/blob/23319bbeb6fb3fbc352d0ed95af9302331df856a/components/product-item.tpl#L32)

Ka siin kasutaks väiksemat.

2021-07-29 12:17 UTC, tanelj approved these changes

2021-07-29 12:31 UTC, merged